"""
Committee registry — maps every city in docs/all_projects_08072026.xlsx to its
planning portal scraper.

Each entry represents one committee (one portal scrape run). Most entries cover
a single city; the Krayot entry covers three cities that share one portal.

Fields:
  committee_name   — display name used in logs and the consolidated report
  cities_hebrew    — list of Hebrew city names matching the 'עיר' column in the
                     projects Excel. The runner filters all_projects by these names.
  scraper          — 'complot' | 'bartech' | None
  site_id          — Complot only; passed to ComplotPermitsAPI(site_id=...)
  base_url         — Bartech only; passed to BartechPermitsAPI(base_url=...)
  permit_url_base  — optional; appended to permit number to produce a clickable
                     URL in the report. None = no URL column.
  include_bakasha_meqdamit — if True, do NOT exclude 'בקשה מקדמית' request
                     category. Required for פתח תקווה and הרצליה (see CLAUDE.md).
  exclude          — True = skip in the nationwide runner
  exclude_reason   — 'proprietary' | 'no_scraper' | 'url_unverified'

Source for scraper metadata: local_committee_scrapers/unified_scraper/
  municipal_scraper/registry/dispatcher.py (revision 2026-02-25).
"""

# ---------------------------------------------------------------------------
# Complot committees
# ---------------------------------------------------------------------------

_COMPLOT = [
    # Tel Aviv District
    {
        'committee_name': 'רמת גן',
        'cities_hebrew': ['רמת גן'],
        'scraper': 'complot',
        'site_id': 3,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'אור יהודה',
        'cities_hebrew': ['אור יהודה'],
        'scraper': 'complot',
        'site_id': 73,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'רמת השרון',
        'cities_hebrew': ['רמת השרון'],
        'scraper': 'complot',
        'site_id': 118,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # Center District
    {
        'committee_name': 'בת ים',
        'cities_hebrew': ['בת ים'],
        'scraper': 'complot',
        'site_id': 81,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'גבעתיים',
        'cities_hebrew': ['גבעתיים'],
        'scraper': 'complot',
        'site_id': 98,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'בני ברק',
        'cities_hebrew': ['בני ברק'],
        'scraper': 'complot',
        'site_id': 75,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'פתח תקווה',
        'cities_hebrew': ['פתח תקווה'],
        'scraper': 'complot',
        'site_id': 84,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': True,   # exception per CLAUDE.md
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'הרצליה',
        'cities_hebrew': ['הרצליה'],
        'scraper': 'complot',
        'site_id': 121,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': True,   # exception per CLAUDE.md
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'הוד השרון',
        'cities_hebrew': ['הוד השרון'],
        'scraper': 'complot',
        'site_id': 33,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'כפר סבא',
        'cities_hebrew': ['כפר סבא'],
        'scraper': 'complot',
        'site_id': 13,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'רעננה',
        'cities_hebrew': ['רעננה'],
        'scraper': 'complot',
        'site_id': 15,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'כפר יונה',
        'cities_hebrew': ['כפר יונה'],
        'scraper': 'complot',
        'site_id': 55,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'ראשון לציון',
        'cities_hebrew': ['ראשון לציון'],
        'scraper': 'complot',
        'site_id': 108,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'רחובות',
        'cities_hebrew': ['רחובות'],
        'scraper': 'complot',
        'site_id': 22,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'מודיעין מכבים רעות',
        'cities_hebrew': ['מודיעין מכבים רעות'],
        'scraper': 'complot',
        'site_id': 82,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'גני תקווה',
        'cities_hebrew': ['גני תקווה'],
        'scraper': 'complot',
        'site_id': 104,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'יבנה',
        'cities_hebrew': ['יבנה'],
        'scraper': 'complot',
        'site_id': 87,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # Haifa District
    {
        'committee_name': 'חיפה',
        'cities_hebrew': ['חיפה'],
        'scraper': 'complot',
        'site_id': 16,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'קרית אתא',
        'cities_hebrew': ['קרית אתא'],
        'scraper': 'complot',
        'site_id': 32,
        'base_url': None,
        'permit_url_base': 'https://handasa.kiryat-ata.org.il/iturbakashot/#request/',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'רכסים',
        'cities_hebrew': ['רכסים'],
        'scraper': 'complot',
        'site_id': 94,   # reches hacarmel
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'מורדות כרמל',
        'cities_hebrew': ['טירת הכרמל', 'נשר'],
        'scraper': 'complot',
        'site_id': 61,
        'base_url': None,
        'permit_url_base': 'https://www.mordotcarmel.org/iturbakashot/#request/',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'ישובי הברון',
        'cities_hebrew': ['זכרון יעקב', 'אור עקיבא', 'בנימינה גבעת עדה', "ג'סר א זרקא"],
        'scraper': 'complot',
        'site_id': 14,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # North District
    {
        'committee_name': 'טבריה',
        'cities_hebrew': ['טבריה'],
        'scraper': 'complot',
        'site_id': 66,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'נהריה',
        'cities_hebrew': ['נהריה'],
        'scraper': 'complot',
        'site_id': 80,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'נצרת',
        'cities_hebrew': ['נצרת'],
        'scraper': 'complot',
        'site_id': 123,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'מגדל העמק',
        'cities_hebrew': ['מגדל העמק'],
        'scraper': 'complot',
        'site_id': 8,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'צפת',
        'cities_hebrew': ['צפת'],
        'scraper': 'complot',
        'site_id': 12,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'יוקנעם עילית',
        'cities_hebrew': ['יוקנעם עילית'],
        'scraper': 'complot',
        'site_id': 63,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'מעלות תרשיחא',
        'cities_hebrew': ['מעלות תרשיחא'],
        'scraper': 'complot',
        'site_id': 120,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # South District
    {
        'committee_name': 'אשדוד',
        'cities_hebrew': ['אשדוד'],
        'scraper': 'complot',
        'site_id': 78,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'אשקלון',
        'cities_hebrew': ['אשקלון'],
        'scraper': 'complot',
        'site_id': 95,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'באר שבע',
        'cities_hebrew': ['באר שבע'],
        'scraper': 'complot',
        'site_id': 105,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'בית שמש',
        'cities_hebrew': ['בית שמש'],
        'scraper': 'complot',
        'site_id': 93,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'דימונה',
        'cities_hebrew': ['דימונה'],
        'scraper': 'complot',
        'site_id': 11,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'אופקים',
        'cities_hebrew': ['אופקים'],
        'scraper': 'complot',
        'site_id': 67,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'שדרות',
        'cities_hebrew': ['שדרות'],
        'scraper': 'complot',
        'site_id': 38,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'אילת',
        'cities_hebrew': ['אילת'],
        'scraper': 'complot',
        'site_id': 56,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'ירוחם',
        'cities_hebrew': ['ירוחם'],
        'scraper': 'complot',
        'site_id': 100,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'קרית גת',
        'cities_hebrew': ['קרית גת'],
        'scraper': 'complot',
        'site_id': 46,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'קרית מלאכי',
        'cities_hebrew': ['קרית מלאכי'],
        'scraper': 'complot',
        'site_id': 107,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'רהט',
        'cities_hebrew': ['רהט'],
        'scraper': 'complot',
        'site_id': 97,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'בית שאן',
        'cities_hebrew': ['בית שאן'],
        'scraper': 'complot',
        'site_id': 54,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # Judea and Samaria
    {
        'committee_name': 'אריאל',
        'cities_hebrew': ['אריאל'],
        'scraper': 'complot',
        'site_id': 122,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'אפרת',
        'cities_hebrew': ['אפרת'],
        'scraper': 'complot',
        'site_id': 126,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'ביתר עילית',
        'cities_hebrew': ['ביתר עילית'],
        'scraper': 'complot',
        'site_id': 35,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'מודיעין עילית',
        'cities_hebrew': ['מודיעין עילית'],
        'scraper': 'complot',
        'site_id': 5,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'מעלה אדומים',
        'cities_hebrew': ['מעלה אדומים'],
        'scraper': 'complot',
        'site_id': 106,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'קרני שומרון',
        'cities_hebrew': ['קרני שומרון'],
        'scraper': 'complot',
        'site_id': 9,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
]

# ---------------------------------------------------------------------------
# Bartech committees
# ---------------------------------------------------------------------------

_BARTECH = [
    # Tel Aviv District
    {
        'committee_name': 'חולון',
        'cities_hebrew': ['חולון'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://hln.bartech-net.co.il',
        'permit_url_base': 'https://hln.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'קרית אונו',
        'cities_hebrew': ['קרית אונו'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://ono.bartech-net.co.il',
        'permit_url_base': 'https://ono.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # Center District
    {
        'committee_name': 'קריות',
        'cities_hebrew': ['קרית מוצקין', 'קרית ביאליק', 'קרית ים'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://www.vkrayot.co.il',
        'permit_url_base': 'https://www.vkrayot.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'אזור',
        'cities_hebrew': ['אזור'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://azr.bartech-net.co.il',
        'permit_url_base': 'https://azr.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'אלעד',
        'cities_hebrew': ['אלעד'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://elad.bartech-net.co.il',
        'permit_url_base': 'https://elad.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'גבעת שמואל',
        'cities_hebrew': ['גבעת שמואל'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://gsm.bartech-net.co.il',
        'permit_url_base': 'https://gsm.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'גדרה',
        'cities_hebrew': ['גדרה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://gedera.bartech-net.co.il',
        'permit_url_base': 'https://gedera.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'גן יבנה',
        'cities_hebrew': ['גן יבנה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://g-yavne.bartech-net.co.il',
        'permit_url_base': 'https://g-yavne.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'לוד',
        'cities_hebrew': ['לוד'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://lod.bartech-net.co.il',
        'permit_url_base': 'https://lod.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'נס ציונה',
        'cities_hebrew': ['נס ציונה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://nes.bartech-net.co.il',
        'permit_url_base': 'https://nes.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'ראש העין',
        'cities_hebrew': ['ראש העין'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://rin.bartech-net.co.il',
        'permit_url_base': 'https://rin.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'רמלה',
        'cities_hebrew': ['רמלה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://handasa.ramla.muni.il',
        'permit_url_base': 'https://handasa.ramla.muni.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'שוהם',
        'cities_hebrew': ['שוהם'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://shm.bartech-net.co.il',
        'permit_url_base': 'https://shm.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'יהוד מונוסון',
        'cities_hebrew': ['יהוד מונוסון'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://yhd.bartech-net.co.il',
        'permit_url_base': 'https://yhd.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'מיצפה אפק',
        'cities_hebrew': ['באר יעקב'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://www.vmm.co.il',
        'permit_url_base': 'https://www.vmm.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'זמורה',
        'cities_hebrew': ['מזכרת בתיה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://www.zmora.org.il',
        'permit_url_base': 'https://www.zmora.org.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'נתניה',
        'cities_hebrew': ['נתניה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://vaadnet.netanyagis.co.il',
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': True,
        'exclude_reason': 'url_unverified',  # non-standard bartech URL, needs testing
    },

    # Jerusalem District
    {
        'committee_name': 'הראל',
        'cities_hebrew': ['מבשרת ציון'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://www.v-harel.co.il',
        'permit_url_base': 'https://www.v-harel.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # Haifa District
    {
        'committee_name': 'חדרה',
        'cities_hebrew': ['חדרה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://hadera.bartech-net.co.il',
        'permit_url_base': 'https://hadera.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'חריש',
        'cities_hebrew': ['חריש'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://www.harishpl.org',
        'permit_url_base': 'https://www.harishpl.org/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'קרית טבעון',
        'cities_hebrew': ['קרית טבעון'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://tivon.bartech-net.co.il',
        'permit_url_base': 'https://tivon.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'פרדס חנה כרכור',
        'cities_hebrew': ['פרדס חנה כרכור'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://vaada.phk.org.il',
        'permit_url_base': 'https://vaada.phk.org.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # North District
    {
        'committee_name': 'עכו',
        'cities_hebrew': ['עכו'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://akko.bartech-net.co.il',
        'permit_url_base': 'https://akko.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'עפולה',
        'cities_hebrew': ['עפולה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://handasa.afula.muni.il',
        'permit_url_base': 'https://handasa.afula.muni.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'כרמיאל',
        'cities_hebrew': ['כרמיאל'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://crm.bartech-net.co.il',
        'permit_url_base': 'https://crm.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'נוף הגליל',
        'cities_hebrew': ['נוף הגליל'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://nzr.bartech-net.co.il',
        'permit_url_base': 'https://nzr.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'קרית שמונה',
        'cities_hebrew': ['קרית שמונה'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://k-shmona.bartech-net.co.il',
        'permit_url_base': 'https://k-shmona.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },

    # South District
    {
        'committee_name': 'נתיבות',
        'cities_hebrew': ['נתיבות'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://netivot.bartech-net.co.il',
        'permit_url_base': 'https://netivot.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'ערד',
        'cities_hebrew': ['ערד'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://arad.bartech-net.co.il',
        'permit_url_base': 'https://arad.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
    {
        'committee_name': 'מצפה רמון',
        'cities_hebrew': ['מצפה רמון'],
        'scraper': 'bartech',
        'site_id': None,
        'base_url': 'https://mizpe.bartech-net.co.il',
        'permit_url_base': 'https://mizpe.bartech-net.co.il/PermitApplicationDetails?Entity_Number=',
        'include_bakasha_meqdamit': False,
        'exclude': False,
        'exclude_reason': None,
    },
]

# ---------------------------------------------------------------------------
# Excluded committees
# ---------------------------------------------------------------------------

_EXCLUDED = [
    # Proprietary systems — no scraper available
    {
        'committee_name': 'תל אביב יפו',
        'cities_hebrew': ['תל אביב יפו'],
        'scraper': None,
        'site_id': None,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': True,
        'exclude_reason': 'proprietary',
    },
    {
        'committee_name': 'ירושלים',
        'cities_hebrew': ['ירושלים'],
        'scraper': None,
        'site_id': None,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': True,
        'exclude_reason': 'proprietary',
    },
    {
        'committee_name': 'קצרין',
        'cities_hebrew': ['קצרין'],
        'scraper': None,
        'site_id': None,
        'base_url': None,
        'permit_url_base': None,
        'include_bakasha_meqdamit': False,
        'exclude': True,
        'exclude_reason': 'proprietary',
    },


    # Cities in projects file without a known scraper
    # Grouped as a convenience; each city is its own logical entry here.
    {
        'committee_name': 'אבו גוש',
        'cities_hebrew': ['אבו גוש'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'אבן יהודה',
        'cities_hebrew': ['אבן יהודה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'אום אל-פחם',
        'cities_hebrew': ['אום אל-פחם'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'אורנית',
        'cities_hebrew': ['אורנית'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'איכסאל',
        'cities_hebrew': ['איכסאל'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'איתמר',
        'cities_hebrew': ['איתמר'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'אליכין',
        'cities_hebrew': ['אליכין'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'אלפי מנשה',
        'cities_hebrew': ['אלפי מנשה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'אלקנה',
        'cities_hebrew': ['אלקנה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'ארסוף',
        'cities_hebrew': ['ארסוף'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'אשדות יעקב מאוחד',
        'cities_hebrew': ['אשדות יעקב מאוחד'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'אשכולות',
        'cities_hebrew': ['אשכולות'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'בית אל',
        'cities_hebrew': ['בית אל'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'בית אריה',
        'cities_hebrew': ['בית אריה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'בית דגן',
        'cities_hebrew': ['בית דגן'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'בני עי"ש',
        'cities_hebrew': ['בני עי"ש'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'בת חפר',
        'cities_hebrew': ['בת חפר'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'גבע בנימין',
        'cities_hebrew': ['גבע בנימין'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'גבעת זאב',
        'cities_hebrew': ['גבעת זאב'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'גליל ים',
        'cities_hebrew': ['גליל ים'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'געש',
        'cities_hebrew': ['געש'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'דאלית אל-כרמל',
        'cities_hebrew': ['דאלית אל-כרמל'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'דיר אל-אסד',
        'cities_hebrew': ['דיר אל-אסד'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'דיר חנא',
        'cities_hebrew': ['דיר חנא'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'חצור הגלילית',
        'cities_hebrew': ['חצור הגלילית'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'חשמונאים',
        'cities_hebrew': ['חשמונאים'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'טורעאן',
        'cities_hebrew': ['טורעאן'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'טלמון',
        'cities_hebrew': ['טלמון'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'יסוד המעלה',
        'cities_hebrew': ['יסוד המעלה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כוכב יאיר צור יגאל',
        'cities_hebrew': ['כוכב יאיר צור יגאל'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כוכב יעקב',
        'cities_hebrew': ['כוכב יעקב'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כפר בלום',
        'cities_hebrew': ['כפר בלום'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כפר ברא',
        'cities_hebrew': ['כפר ברא'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כפר ורדים',
        'cities_hebrew': ['כפר ורדים'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כפר כנא',
        'cities_hebrew': ['כפר כנא'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כפר קאסם',
        'cities_hebrew': ['כפר קאסם'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כפר שמריהו',
        'cities_hebrew': ['כפר שמריהו'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'כפר תבור',
        'cities_hebrew': ['כפר תבור'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'לפיד',
        'cities_hebrew': ['לפיד'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מבוא מודיעים',
        'cities_hebrew': ['מבוא מודיעים'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מגדל',
        'cities_hebrew': ['מגדל'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מדרשת בן-גוריון',
        'cities_hebrew': ['מדרשת בן-גוריון'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מוצא עילית',
        'cities_hebrew': ['מוצא עילית'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מחניים',
        'cities_hebrew': ['מחניים'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מעלה אפרים',
        'cities_hebrew': ['מעלה אפרים'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מעלה עמוס',
        'cities_hebrew': ['מעלה עמוס'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מצפה שלם',
        'cities_hebrew': ['מצפה שלם'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מרכז שפירא',
        'cities_hebrew': ['מרכז שפירא'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'מתן',
        'cities_hebrew': ['מתן'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'ניר אליהו',
        'cities_hebrew': ['ניר אליהו'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'סח\'נין',
        'cities_hebrew': ['סח\'נין'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'עמנואל',
        'cities_hebrew': ['עמנואל'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'עראבה',
        'cities_hebrew': ['עראבה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'עתלית',
        'cities_hebrew': ['עתלית'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'פוריה כפר עבודה',
        'cities_hebrew': ['פוריה כפר עבודה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'פוריידיס',
        'cities_hebrew': ['פוריידיס'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'פרדסיה',
        'cities_hebrew': ['פרדסיה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'פרוד',
        'cities_hebrew': ['פרוד'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'צופים',
        'cities_hebrew': ['צופים'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'צור הדסה',
        'cities_hebrew': ['צור הדסה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'צור יצחק',
        'cities_hebrew': ['צור יצחק'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'צור נתן',
        'cities_hebrew': ['צור נתן'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'קדימה צורן',
        'cities_hebrew': ['קדימה צורן'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'קיסריה',
        'cities_hebrew': ['קיסריה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'קרית יערים',
        'cities_hebrew': ['קרית יערים'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'קרית עקרון',
        'cities_hebrew': ['קרית עקרון'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'רוחמה',
        'cities_hebrew': ['רוחמה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'ריחן',
        'cities_hebrew': ['ריחן'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'רמת ישי',
        'cities_hebrew': ['רמת ישי'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'שדה ורבורג',
        'cities_hebrew': ['שדה ורבורג'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'שלומי',
        'cities_hebrew': ['שלומי'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'שערי תקווה',
        'cities_hebrew': ['שערי תקווה'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'שפרעם',
        'cities_hebrew': ['שפרעם'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'תל מונד',
        'cities_hebrew': ['תל מונד'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
    {
        'committee_name': 'תנובות',
        'cities_hebrew': ['תנובות'],
        'scraper': None, 'site_id': None, 'base_url': None, 'permit_url_base': None,
        'include_bakasha_meqdamit': False, 'exclude': True, 'exclude_reason': 'no_scraper',
    },
]

# ---------------------------------------------------------------------------
# Combined registry
# ---------------------------------------------------------------------------

COMMITTEES = _COMPLOT + _BARTECH + _EXCLUDED


def coverage_summary():
    """Print a summary of scraper coverage against the projects file."""
    scraped = [c for c in COMMITTEES if not c['exclude']]
    excl_prop = [c for c in COMMITTEES if c['exclude'] and c['exclude_reason'] == 'proprietary']
    excl_no = [c for c in COMMITTEES if c['exclude'] and c['exclude_reason'] == 'no_scraper']
    excl_unverified = [c for c in COMMITTEES if c['exclude'] and c['exclude_reason'] == 'url_unverified']
    complot_active = [c for c in scraped if c['scraper'] == 'complot']
    bartech_active = [c for c in scraped if c['scraper'] == 'bartech']

    print(f"Active committees : {len(scraped)}")
    print(f"  Complot         : {len(complot_active)}")
    print(f"  Bartech         : {len(bartech_active)}")
    print(f"Excluded          : {len(COMMITTEES) - len(scraped)}")
    print(f"  Proprietary     : {len(excl_prop)}")
    print(f"  No scraper      : {len(excl_no)}")
    print(f"  URL unverified  : {len(excl_unverified)}")
    print(f"Total entries     : {len(COMMITTEES)}")


if __name__ == '__main__':
    coverage_summary()
