"""
Incremental runner for Bat Yam -- fast alternative to the full scrape (~10 min vs ~80 min).

Requires a prior full run to have produced:
  outputs/bat_yam_fresh.xlsx          -- full permit history (identity fields)
  outputs/bat_yam_matched_cache.json  -- permit numbers matched to BO projects
                                         (generated by matcher.run with matched_cache_path=...)

Two phases:
  Phase A -- re-check ~600 matched permits (status_advanced candidates)
             Calls GetBakashaFile directly; skips the 9,600-row list fetch.
  Phase B -- scrape 2025-2026 only (~500-800 permits)
             Catches new_permit and untracked rows filed in the past two years.

Output: outputs/bat_yam_report.xlsx (same format as full run).
        outputs/bat_yam_matched_cache.json is refreshed after the matcher runs.
"""

import json
import os
import sys
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scrapers.complot.api_scraper import ComplotPermitsAPI
from transform import matcher

SITE_ID         = 81
CITY            = 'בת ים'
PROJECTS_PATH   = 'docs/bat_yam.xlsx'
FRESH_PATH      = 'outputs/bat_yam_fresh.csv'
CACHE_PATH      = 'outputs/bat_yam_matched_cache.json'
REPORT_PATH     = 'outputs/bat_yam_report.xlsx'
RECENT_YEARS    = [2025, 2026]

# ---------------------------------------------------------------------------
# Load matched permit numbers from cache
# ---------------------------------------------------------------------------
if not os.path.exists(CACHE_PATH):
    print(f'[ERROR] Cache not found: {CACHE_PATH}')
    print('  Run the full scrape + matcher with matched_cache_path first.')
    sys.exit(1)

with open(CACHE_PATH, encoding='utf-8') as f:
    cache = json.load(f)
matched_numbers = set(cache.get('matched_permit_numbers', []))
print(f'[INFO] Cache loaded: {len(matched_numbers)} matched permit numbers')

# ---------------------------------------------------------------------------
# Load identity fields for matched permits from last full scrape
# ---------------------------------------------------------------------------
if not os.path.exists(FRESH_PATH):
    print(f'[ERROR] Full scrape output not found: {FRESH_PATH}')
    print('  Run scripts/run_bat_yam.py first.')
    sys.exit(1)

fresh_df = pd.read_csv(FRESH_PATH, encoding='utf-8-sig')
fresh_df.columns = [c.strip() for c in fresh_df.columns]
phase_a_df = fresh_df[fresh_df['request_number'].astype(str).isin(matched_numbers)]
phase_a_records = phase_a_df.to_dict('records')
print(f'[INFO] Phase A: {len(phase_a_records)} matched permits to refresh')

# ---------------------------------------------------------------------------
# Phase A -- refresh status for matched permits
# ---------------------------------------------------------------------------
scraper = ComplotPermitsAPI(site_id=SITE_ID, city_name_hebrew=CITY, b_params=[])
phase_a_updated = scraper.scrape_targeted(phase_a_records)

# ---------------------------------------------------------------------------
# Phase B -- full scrape of recent years (new permits only)
# ---------------------------------------------------------------------------
print(f'[INFO] Phase B: scraping years {RECENT_YEARS}...')
scraper_recent = ComplotPermitsAPI(
    site_id=SITE_ID,
    city_name_hebrew=CITY,
    b_params=RECENT_YEARS,
)
phase_b_all = scraper_recent.scrape()
# Exclude permits already refreshed in Phase A to avoid duplicates
phase_b = [p for p in phase_b_all if str(p['request_number']) not in matched_numbers]
print(f'[INFO] Phase B: {len(phase_b_all)} scraped, {len(phase_b)} new (not in Phase A cache)')

# ---------------------------------------------------------------------------
# Combine and save merged permits file
# ---------------------------------------------------------------------------
combined_df = pd.DataFrame(phase_a_updated + phase_b)
os.makedirs('outputs', exist_ok=True)
incremental_path = 'outputs/bat_yam_fresh_incremental.csv'
combined_df.to_csv(incremental_path, index=False, encoding='utf-8-sig')
print(f'[OK] Combined permits saved to {incremental_path} ({len(combined_df)} rows)')

# ---------------------------------------------------------------------------
# Run matcher
# ---------------------------------------------------------------------------
matcher.run(
    projects_path=PROJECTS_PATH,
    permits_path=incremental_path,
    city_hebrew=CITY,
    output_path=REPORT_PATH,
    matched_cache_path=CACHE_PATH,
)
